//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionUsuarios.WcfService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDocumento
    {
        public int Id { get; set; }
        public string TipoDocumento { get; set; }
    }
}
