//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministracionUsuarios.WcfService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UserId { get; set; }
        public string NombreCompleto { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Pais { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
    }
}
